# Generated by Django 3.0.2 on 2020-01-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='contact',
            field=models.BigIntegerField(),
        ),
    ]
